### ISSUE TITLE
custom-ami: changing the torque version

### ISSUE THREAD

**Issue by snamburi3** [awslabs/cfncluster#149]
cfncluster and chef recipes use torque 6.0.2. I want to install the version 4.2.10 (my scripts use old version). What is the best way to modify the installation?

**Comment by f403** [comment]
I did the following:
- modified *version* and *url* in `cfncluster-cookbook/attributes/default.rb`;
- packed it into archive;
- uploaded to S3 making it publicly available;
- used custom_chef_cookbook parameter to provide a new uri.

Not sure if this is the best way because you will need to update your custom archive with each cfncluster update. But it worked for me.

**Comment by snamburi3** [comment]
Thanks, @f403!
