### ISSUE TITLE
How to Submit Multiple Jobs per Node

### ISSUE THREAD

**Issue by marcofurbo** [awslabs/cfncluster#196]
We are using SLURM, and we'd like to submit multiple jobs to each node. We are going to be using the m4.16xlarge instances, and we want to take advantage of all of the 64 cores in each instance.

What is the "cfncluster" way to get this done?

**Comment by bwbarrett** [comment]
There isn't a "cfncluster way" to do what you want, in that CfnCluster tries to be very hands-off in configuring the scheduler.  It provides a basic `/opt/slurm/etc/slurm.conf` configured as a good starting point for most small HPC scheduler needs.  CfnCluster won't modify the config file after the initial setup (actually, this isn't quite true, as stop/start will rebuild the master node, but otherwise CfnCluster won't rebuild config files on the master node), so you can edit the config file to fit your particular needs.  Slurm has some great documentation on its config file here: https://slurm.schedmd.com/slurm.conf.html.

If you want to automate updating the config file on new cluster builds, a custom bootstrap action can be used to automate what you want: http://cfncluster.readthedocs.io/en/latest/pre_post_install.html

**Comment by marcofurbo** [comment]
We see this line in the config for example:

NodeName=ip-172-31-5-252,ip-172-31-13-210,ip-172-31-5-242 Procs=1 State=UNKNOWN

According to Slurm docs, "Procs=1" seems to be telling Slurm to treat each node like they have 1 processor. However, we can't edit that line, as it seems to be written dynamically by cfncluster or some other process whenever a scaling action is triggered. 

Do you know of a way to get around this and make sure Slurm/cfncluster treats each node as if it has the correct number of vCPUs?
