### ISSUE TITLE
Can the master node be launched as spot instance?

### ISSUE THREAD

**Issue by mistycheney** [awslabs/cfncluster#214]
Currently the default behavior is to launch the master node as on-demand. This is the case even if I set "cluster_type=spot". Is there a way to launch the master node as spot instance instead?

**Comment by mkuchnik** [comment]
You should be able to change the CloudFormation template to get what you want (MasterInstance is spot), but I suspect any spot revocation of the master node will result in the whole cluster failing with no recovery.

**Comment by mistycheney** [comment]
Can you point to where in the CloudFormation template I should make the change?

**Comment by mkuchnik** [comment]
MasterServer would have to become a spot fleet. Then you would have to have to make sure the initialization procedure works. It's a bit more complicated than I thought, since using a spot fleet means you have to adjust the parameters in the MasterServer. Is there a particular reason you want to use spot for the master server? Using a small on-demand instance would be pretty cost effective. If you're worried about having a weak master node, you can find a way to SSH directly into the compute nodes.

Alternatively, you could default to launching instances manually via tools like Boto and then find a way to coordinate that with the rest of the system.

**Comment by bwbarrett** [comment]
@mistycheney, the short answer is that there isn't a good way to use Spot for the master.  You'd have to use Spot Fleet or change the master to be an autoscaling group, both of which would break a bunch of follow-on assumptions.  And then once it's working, you're not going to end up where you want, because the master failing is essentially suicide to the cluster; there's no recovery if the master node is lost.

If you're worried about price, a t2.small can act as a master node without an problem (and in many cases, a t2.micro is sufficient).  You might run into trouble building large software packages on the master node, but using compute nodes to build should work around that problem.
