### ISSUE TITLE
cfncluster SGE

### ISSUE THREAD

**Issue by mkaja** [awslabs/cfncluster#227]
hi - can you tell us if LSF is an option when using CfnCluster? do we need a commercial license to run LSF. Is the closet thing to LSF that CfnCluster supports is SGE or Slurm. we are asking because we need to convert scripts from LSF to CfnCluster scripts and want to know which supported queuing system is closest to LSF

**Comment by mohanasudhan** [comment]
we have sge, torque, or slurm in our scheduler list. @bwbarrett  any idea on which supported queuing system is closest to LSF?

**Comment by bwbarrett** [comment]
We answered this question on the AWS Forums, but for those who don't have Forums access, the short answer is that it really depends on which features of LSF that @mkaja's application is using.  Some of LSF's features don't have a match in SGE, Torque, or SLURM.  Some are pretty easy to emulate.  LSF also has EC2 support, so it can manage instances (rather than the other way around), which may be simpler than using CfnCluster for some workloads.
