### ISSUE TITLE
Template_url for Cfncluster on GovCloud

### ISSUE THREAD

**Issue by LegionH** [awslabs/cfncluster#233]
I am trying to create a cluster with cfncluster on my GovCloud instance but I get a 403 error.  I'm not sure why or what permissions I do not have.  I created the bucket so I cant imagine I don't have rights to it.
The syntax for template_url is set to https://s3-us-gov-west-1.amazonaws.com/the_name_of_my_bucket/cfncluster.cfn.json
I have read the configure guide, watched youtube videos, and looked for others with this issue but I cannot find anything that helps.
Any advice would be welcome.  Thank you.

**Comment by mohanasudhan** [comment]
we haven't got to support gov cloud yet https://github.com/awslabs/cfncluster/blob/develop/cloudformation/cfncluster.cfn.json#L1963

**Comment by bwbarrett** [comment]
@mohanasudhan is correct, out of the box CfnCluster does not support the GovCloud region (nor the AWS (China) region).  In the case of GovCloud, CfnCluster can be made to work, but two components are left as an exercise to the reader, providing a CloudFormation template and an AMI (although it sounded like you already knew that).  If your CfnCluster configuration file specifies a `template_url` and `custom_ami` pointing to resources in your S3 bucket, the rest of CfnCluster should "just work" in GovCloud.

I think you're running into https://github.com/awslabs/cfncluster/issues/144, which I haven't had time to dig into, beyond determining that the (awful) solution of making the template world-accessible did, indeed, work.

**Comment by mohanasudhan** [comment]
with respect to s3 access. I too came across the same issue sometime back. I digged in by didn't spend much time in fix, went with workaround for the time being. 

My observation:
This is the code which does sanity check on template URL https://github.com/awslabs/cfncluster/blob/develop/cli/cfncluster/config_sanity.py#L92

It expect schema to be s3:// to skip validation --> but in this case cloudformation throws an exception "The specified url must be an Amazon S3 URL." - I see this specific issue is fixed in aws cli side but need to see why its not working in cfncluster https://github.com/aws/aws-cli/pull/2331

In case of rest of the schema we simply call `urllib.request.urlopen(resource_value)` to validate file presence. The request is not using any iam permission entity to access any restricted s3 files, hence we need to go with public permission here.

**Comment by LegionH** [comment]
Thank you very much for the information.  This was very helpful.

**Comment by LegionH** [comment]
Can you provide any resources with more information on how to open S3 up to get this to work?  I just want to do some testing to security isn't much of a concern.
I have placed my cfncluster.cfn.json file on my bucket and changed Public Access to Yes for all options.
![image](https://user-images.githubusercontent.com/32465993/31184099-76435f7c-a8f6-11e7-9fef-f25fe8f21536.png)
What else am I missing?

**Comment by rajachan** [comment]
From your screenshot, it looks like you have opened up the bucket to public access already. If you are having issues with the individual object's permissions, right-click on your template object and select "Make public". 

![screen shot 2017-10-09 at 11 20 38 am](https://user-images.githubusercontent.com/742736/31352536-f643dfa8-ace3-11e7-831d-e42b0ba085bc.png)

[This document](http://docs.aws.amazon.com/AmazonS3/latest/dev/s3-access-control.html) should provide more guidance on managing permissions with S3.

**Comment by LegionH** [comment]
Thank you very much rajachan!  That was exactly what I was missing.  Now to figure out the custom AMI...
