### ISSUE TITLE
Is it possible to customize AMI?

### ISSUE THREAD

**Issue by michaelxu2014** [awslabs/cfncluster#24]
I have a prebuilt AMI and I want to launch a cluster with all worker nodes created from the customized AMI. I am not sure if it is possible to support this mode. 
Besides, how can I use the public AMI? For example, the AMI name is amzn-ami-hvm-2014.09.1.x86_64-ebs from the source amazon/amzn-ami-hvm-2014.09.1.x86_64-ebs.

In the config file, I cannot access the template URL: https://s3.amazonaws.com/cfncluster-us-east-1/templates/cfncluster.cfn.json. So how can I find other template available?

Thanks!

**Comment by cgibioinformatics** [comment]
Hi, I'm having same issue configuring ubuntu os AMI and launch. I'm wondering what could be wrong? Thanks

**Comment by mohanasudhan** [comment]
@cgibioinformatics  May I understand why you want to customized AMI ?

Suggestion: 
1. Please look at pre_install/post_install option of cfncluster instead of creating custom AMI
2. If you still want to create AMI, Please use packer command to create ami (E.g. for ubuntu14 https://github.com/awslabs/cfncluster-cookbook/blob/develop/packer_ubuntu1404.json)
