### ISSUE TITLE
1.4.0 'update' function fail: "global name 'logger' is not defined"

### ISSUE THREAD

**Issue by leungrc** [awslabs/cfncluster#271]
I've just recently upgraded to version 1.4.0 of cfncluster. Previously I was using version 1.3.1 and I didn't have any particular problems with it, including the 'update' function. However, after upgrading to version 1.4.0, and after trying to 'update' to reflect changes in my ~/.cfncluster/config file, I see the following error (my cluster name is 'mymastercluster'): 

```
cfncluster update mymastercluster
2017-12-03T08:08:12.960 - INFO - cfncluster.cli - CfnCluster cli starting
Updating: mymastercluster
Traceback (most recent call last):
  File "/usr/local/bin/cfncluster", line 9, in <module>
    load_entry_point('cfncluster==1.4.0', 'console_scripts', 'cfncluster')()
  File "/Library/Python/2.7/site-packages/cfncluster/cli.py", line 142, in main
    args.func(args)
  File "/Library/Python/2.7/site-packages/cfncluster/cli.py", line 43, in update
    cfncluster.update(args)
  File "/Library/Python/2.7/site-packages/cfncluster/cfncluster.py", line 147, in update
    logger.debug((config.template_url, config.parameters))
NameError: global name 'logger' is not defined
```

Other than changing my `master_instance_type`, I haven't made any other changes to my config file. The only change is upgrading cfncluster from version 1.3.1 to 1.4.0.

**Comment by mohanasudhan** [comment]
Apologies for the inconvenience caused because of upgrade. Looking at the code, I narrow down the problem is because of PR https://github.com/awslabs/cfncluster/commit/268220f7c78def4a7540442b8f1b22311fcd673d#diff-078476ef6bcf491ad1fab19242406003

Specifically because of this line https://github.com/awslabs/cfncluster/commit/268220f7c78def4a7540442b8f1b22311fcd673d#diff-078476ef6bcf491ad1fab19242406003L27

As far as I see only update function is broken, Please terminate and create new cluster (to unblock you). We will try to fix this issue asap and release it today.

**Comment by mohanasudhan** [comment]
@leungrc We plan to release cfncluster 1.4.1 in couple of days with above fix.

**Comment by leungrc** [comment]
@mohanasudhan  Thanks for addressing the issue!
