### ISSUE TITLE
slurm job requesting 10 nodes, persistently cycles between 5 and 6 nodes 

### ISSUE THREAD

**Issue by karlvirgil** [awslabs/cfncluster#296]
I have submitted a slurm job requesting 10 nodes (no other jobs running at the time).  The queue builds up to 5 nodes, then cycles between 5 and 6 nodes without ever reaching 10 nodes.  I've set the maximum number of nodes to 50 for my cfncluster instance.  Looking in the autoscaling group logs, I see that about every ten minutes a new node is added, then deleted (attached).  This has been going on for more than 12 hours...
![screen shot 2018-01-13 at 10 14 25](https://user-images.githubusercontent.com/6791257/34907314-9a5c79a4-f84a-11e7-9274-73f348a7594d.png)

**Comment by mohanasudhan** [comment]
@karlvirgil can you share sqswatcher.log under /var/logs on master + it would be great to have your cfncluster config as well (Don't forgot to mask your credential/secrets) ?

**Comment by karlvirgil** [comment]
Here they are

[sqswatcher.txt](https://github.com/awslabs/cfncluster/files/1632627/sqswatcher.txt)
[config.txt](https://github.com/awslabs/cfncluster/files/1632631/config.txt)

**Comment by mohanasudhan** [comment]
Seems you using this cluster for more than a month, from when you seeing this behaviour ?

**Comment by karlvirgil** [comment]
Since last Friday (Jan 26).

-Karl

**Comment by mohanasudhan** [comment]
And I see desired count in your ASG is set to 5, creating a suspicion on your job (which you say its requesting 10 node)

**Comment by mohanasudhan** [comment]
you mean jan 12 ?

**Comment by karlvirgil** [comment]
Yes, sorry.  Jan 12.

**Comment by karlvirgil** [comment]
My job is requesting 10 nodes.  Heres the output from the squeue command:
          ....centos....
  JOBID PARTITION     NAME     USER    STATE       TIME TIME_LIMI  NODES PRIORITY QOS NODELIST(REASON)
    690   compute ebyycncr   centos  PENDING       0:00 UNLIMITED     10 4294901759 (null) (Resources)

And here's my sbatch script that I used to submit.

#!/bin/bash
#SBATCH --job-name=ebyycncre
#SBATCH --partition=compute
#SBATCH --account=centos
#SBATCH --threads-per-core=1
#SBATCH --sockets-per-node=2
#SBATCH --cores-per-socket=18
#SBATCH --nodes=10
#SBATCH --mail-type=ALL
#SBATCH --output=./s%j
#SBATCH --no-requeue

mpirun -np 360 fireFoam -parallel

**Comment by mohanasudhan** [comment]
From the logs,  issue start happening at 2018-01-13 01

2018-01-13 01:22:02,380 INFO [slurm:addHost] Adding ip-10-15-20-33
2018-01-13 01:22:02,452 INFO [slurm:__restartSlurm] Connecting to host: ip-10-15-20-33 iter: 0
2018-01-13 01:22:02,468 INFO [transport:_log] Connected (version 2.0, client OpenSSH_7.4)
2018-01-13 01:22:02,624 INFO [transport:_log] Authentication (publickey) successful!
2018-01-13 01:31:06,563 INFO [sqswatcher:pollQueue] eventType=autoscaling:EC2_INSTANCE_TERMINATE
2018-01-13 01:31:06,564 INFO [sqswatcher:pollQueue] instanceId=i-014ce49a5e620a405
2018-01-13 01:31:06,597 INFO [slurm:removeHost] Removing ip-10-15-20-125
2018-01-13 01:33:08,098 INFO [sqswatcher:pollQueue] eventType=cfncluster:COMPUTE_READY
2018-01-13 01:33:08,098 INFO [sqswatcher:pollQueue] instanceId=i-051f4354cba25eb80
2018-01-13 01:33:08,159 INFO [sqswatcher:pollQueue] Adding Hostname: [Reservation:r-03bad53f851b20f77]

**Comment by mohanasudhan** [comment]
We use https://github.com/awslabs/cfncluster-cookbook/blob/develop/templates/default/publish_pending.slurm.erb script to get pending jobs request and publish it to cloudwatch. We like scaling property of ASG with this cloudwatch metrics

I request two details to help us debug. 

1) can you find pending value manually and update us ? I copy pasted above script for reference

`PATH=/bin:/usr/bin:/usr/local/bin
export PATH

. /opt/cfncluster/cfnconfig

if [ "$cfn_proxy" != "NONE" ]; then
  export http_proxy=$cfn_proxy; export https_proxy=$cfn_proxy
  export HTTP_PROXY=$cfn_proxy; export HTTPS_PROXY=$cfn_proxy
  export no_proxy=169.254.169.254; export NO_PROXY=169.254.169.254
fi

pending=$(/opt/slurm/bin/squeue -r -h -o '%t %D' | awk '$1 == "PD" { total = total + 1} END {print total}')`

2) Can you capture cloudwatch metrics graph for your cluster. Cloudwatch metrics name will be in this format <CfnclusterName>-AddCapacityAlarm-<ID> ?

**Comment by karlvirgil** [comment]
```
 $)cat script.sh
PATH=/bin:/usr/bin:/usr/local/bin
export PATH

. /opt/cfncluster/cfnconfig

if [ "$cfn_proxy" != "NONE" ]; then
    export http_proxy=$cfn_proxy; export https_proxy=$cfn_proxy
    export HTTP_PROXY=$cfn_proxy; export HTTPS_PROXY=$cfn_proxy
    export no_proxy=169.254.169.254; export NO_PROXY=169.254.169.254
fi

pending=$(/opt/slurm/bin/squeue -r -h -o '%t %D' | awk '$1 == "PD" { total = total + 1} END {print total}')
echo $pending
```
Then
`source script.sh
`
The value of $pending comes back as 1, even though 
`/opt/slurm/bin/squeue -r -h -o '%t %D'`
gives
`PD 10
`
as output.

**Comment by karlvirgil** [comment]
As for your second request, I don't follow how to go about capturing cloudwatch metrics graphs.  Where do I do this?  In the console?

**Comment by mohanasudhan** [comment]
ya go to cloudwatch console. click Alarms [left pane] ->  click {CfnclusterName}-AddCapacityAlarm-{ID}  [right pane] -> click on graph [bottom pane] -> graph will expand, change time period to 3 days

sample. click on circle'd graph.

![screen shot 2018-01-15 at 12 16 12 pm](https://user-images.githubusercontent.com/1933952/34960183-ab391f48-f9ee-11e7-874e-68fe296ae6f3.png)

**Comment by karlvirgil** [comment]
So, I only have AddCapacityAlarm2, and no AddCapacityAlarm.  Here it is:
![screen shot 2018-01-15 at 15 28 08](https://user-images.githubusercontent.com/6791257/34960452-d73477f4-fa08-11e7-9d4f-9e196395045d.png)

**Comment by mohanasudhan** [comment]
That's strange. Looking at your cfncluster config you should have both. Can you please capture scaling policies under ASG { in console } as well ?

Ask is just to confirm your config and current infrastructure are same.

**Comment by mohanasudhan** [comment]
ok then maybe you need to reconfirm under cloudwatch -> alarms again (check under ALARM, INSUFFICIENT, and OK)

But I got what I want, pending graph was always at 5 and did not go to 10. This explains ASG behaviour. So the problem is with this script

`pending=$(/opt/slurm/bin/squeue -r -h -o '%t %D' | awk '$1 == "PD" { total = total + 1} END {print total}')`

**Comment by mohanasudhan** [comment]
Think I got the issue here, there is no problem with above script or infrastructure (sorry for the confusion)

I believe it's racing condition. 
1. According to your scaling configuration, we add 1 instance every 600 second (10 mins) in order to meet your pending job, at the same time we try to terminate 1 instance from your cluster if nothing is running in scheduler (in this case we wait for 95% of hour percentile which is 57 min, before terminating your instance) - FYI https://github.com/awslabs/cfncluster-node/blob/develop/nodewatcher/nodewatcher.py#L163

2. In this case, you have 1 pending job and 0 running job, so we add 5 instance till 50 mins (10 mins interval) and we start terminating 1 instance every 57 min of its creation. The cycle continues and it's a racing condition.

Suggestion. update your scaling property, such that we can meet all scaling demand with in 57 mins.
http://cfncluster.readthedocs.io/en/latest/configuration.html#scaling-cooldown

current property:
[scaling custom]
scaling_period = 60
scaling_threshold = 1
scaling_adjustment = 1
scaling_evaluation_periods = 1
scaling_cooldown = 600
scaling_threshold2 = 200
scaling_adjustment2 = 20
scaling_period2 = 60

proposed property:
[scaling custom]
scaling_period = 60
scaling_threshold = 1
scaling_adjustment = 1
scaling_evaluation_periods = 1
scaling_cooldown = 200 (will work for scaling update 10 instances )
scaling_threshold2 = 200
scaling_adjustment2 = 20
scaling_period2 = 60

**Comment by karlvirgil** [comment]
That worked!  Thanks!
