### ISSUE TITLE
SGE not registering new nodes

### ISSUE THREAD

**Issue by badaldavda** [awslabs/cfncluster#312]
cfn cluster version 1.3.2
updated to cfn cluster version 1.4.2

SGE is not registering new nodes suddenly after working for a long time -

Also in SGE - 
In $SGE_ROOT/default/spool/qmaster/messages, I see this denial message: 

02/01/2018 14:26:43|  main|ip-172-17-1-33|I|starting up SGE 8.1.9 (lx-amd64)
02/01/2018 14:45:46|listen|ip-172-17-1-33|C|denied: request for user "centos" does not match credentials for connection <ip-172-17-1-33.us-west-2.compute.internal,execd,1>

I asked them to update their cluster and when they are trying to update their cfncluster using -
cfncluster update --cluster-template QM

But it resulted in UPDATE_ROLLBACK  The update failed because "Interface: [eni-xxxxxxxxxx] in use"

This interface is the MasterInterface that is created using cloudformation.

Attached cfn-init* log files.

Kindly help me in figuring out what the issue is.

[cfn-init-cmd.log](https://github.com/awslabs/cfncluster/files/1694344/cfn-init-cmd.log)
[cfn-init.log](https://github.com/awslabs/cfncluster/files/1694345/cfn-init.log)
[cfn-wire.log](https://github.com/awslabs/cfncluster/files/1694346/cfn-wire.log)

**Comment by rajachan** [comment]
From your cookbook logs, I see there was a failure with the sysctl cookbook (version 0.10.2). This was a known issue, and was fixed in CfnCluster v1.4.0 (see https://github.com/awslabs/cfncluster-cookbook/commit/ea98f132f44a44941bbf8386f7de46395ff556ae), which makes me believe CfnCluster CLI was not updated to v1.4.2 in your case. 

As for the cluster update failing, what were the changes made to the original config or the custom template that required an update of the CloudFormation stack?

**Comment by jw-feng** [comment]
Hi, I am the customer that Badal is working with. 

cfncluster version is 1.4.2 on my laptop.  I updated from 1.3.x about five days ago.  After updating to 1.4.2, I created a new cluster named [cluster MD] without any issues.  I don't remember modifying the [cluster QM] configuration.  

Here is my config file with confidential information removed.

[aws]
aws_region_name = XXX
aws_access_key_id = XXX
aws_secret_access_key = XXX

[cluster default]
vpc_settings = XXX
key_name = XXX

[vpc XXX]
master_subnet_id = subnet-XXX
vpc_id = vpc-YYY
use_public_ips = false

[global]
update_check = true
sanity_check = true
cluster_template = QM

[cluster QM]
vpc_settings = XXX
key_name = jwfeng
base_os = centos7
scheduler = sge
master_instance_type = t2.small
compute_instance_type = c4.2xlarge
initial_queue_size = 1
max_queue_size = 20
maintain_initial_size = false
master_root_volume_size = 1000
compute_root_volume_size = 100
pre_install = https://s3-us-west-2.amazonaws.com/url1
post_install = https://s3-us-west-2.amazonaws.com/url2
cwl_region = us-west-2

[cluster MD]
vpc_settings = XXX
key_name = xxx
base_os = centos7
scheduler = sge
master_instance_type = t2.small
compute_instance_type = p3.2xlarge
initial_queue_size = 1
max_queue_size = 4
maintain_initial_size = true
master_root_volume_size = 1000
compute_root_volume_size = 1000
pre_install = https://s3-us-west-2.amazonaws.com/url1
post_install = https://s3-us-west-2.amazonaws.com/url2
cwl_region = us-west-2
cwl_log_group = MD

**Comment by rajachan** [comment]
@jw-feng, a `cfncluster update` would be necessary only when you change some parameter in the config file (say, when you want to change the compute instance type). An update of the CloudFormation stack is not necessary when you update the CfnCluster CLI. In fact, since each CfnCluster release uses its own set of AMIs and cookbooks that are significantly different from previous versions, running `cfncluster update` on a cluster launched with an older version of the CLI is not supported, and could leave the cluster in an undefined state. This would explain the behavior you are seeing with your QM cluster and why launching the MD cluster did not pose any issues.

Like I mentioned in my previous comment, the actual error you are seeing with CfnCluster v1.3.2 is a known issue (https://github.com/awslabs/cfncluster-cookbook/issues/30) that has since been fixed. The best way forward is for you to relaunch your cluster with the v1.4.2 release.
