### ISSUE TITLE
Unable to launch a cluster using custom AMI and cfncluster 1.4.2

### ISSUE THREAD

**Issue by adavanisanti** [awslabs/cfncluster#318]
Hi, I am unable to launch a cluster using cfncluster version 1.4.2. I am using instructions from [here](http://cfncluster.readthedocs.io/en/latest/ami_customization.html) for creating a custom AMI. 

Could you help me fix this problem or suggest where I need to look?

Thanks
Santi

Error message is:
```
  - AWS::EC2::Instance MasterServer Received FAILURE signal with UniqueId i-025c12d313781c9ca
```

Config file:

```
[aws]
aws_region_name = us-west-2
aws_access_key_id = xxxxx
aws_secret_access_key = xxxxxx

[cluster default]
vpc_settings = public
key_name = xxxxxxxxx
master_instance_type = m4.large
compute_instance_type = m4.large
initial_queue_size = 2
max_queue_size = 2
maintain_initial_size = true
placement_group = DYNAMIC
master_root_volume_size = 100
compute_root_volume_size = 100
base_os = ubuntu1604
ebs_settings = custom
scheduler = slurm
custom_ami = ami-xxxxxx
[ebs custom]
volume_type = gp2
volume_size = 100

[vpc public]
master_subnet_id = subnet-xxxxxx
vpc_id = vpc-xxxxxx

[global]
update_check = true
sanity_check = true
cluster_template = default
```

**Comment by bwbarrett** [comment]
The instance was terminated by an API call, likely because the instance start-up scripts failed and CloudFormation rolled back the stack.  You're using a custom AMI, which brings in an added level of software that has to work correctly.  Your best bet is to build the cluster with the `--norollback` option to the `cfncluster create` call and then look at `/var/log/cloud-init*` files for signs of why the build-out failed and the Chef recipes didn't cause a success callback to CloudFormation.

**Comment by adavanisanti** [comment]
Thanks @bwbarrett. Checking the logs helped resolve this issue. Problem was with ssh keys in `.ssh` folder. I had a private key but not public key in `.ssh` and chef seems to be looking for that. I am not sure about the reason behind that check.
