### ISSUE TITLE
DELETE_FAILED

### ISSUE THREAD

**Issue by karlvirgil** [awslabs/cfncluster#359]
I am trying to delete a cfncluster instance, and get this error message:

> $ )cfncluster delete test-billing
> Deleting: test-billing
> Status: DELETE_FAILEDst-billing - DELETE_FAILED
> Cluster did not delete successfully. Run 'cluster delete cfncluster-test-billing' again

No matter how many times I run it, the delete keeps failing.  Any way to manually delete it?

**Comment by bwbarrett** [comment]
There's no way to delete it from CfnCluster.  However, if you look at the CloudFormation stack information in the console, it should include data on why the delete failed.  Usually, it's because some resource is still in use (or was deleted outside of CloudFormation and now CloudFormation is confused).  It's usually pretty obvious of next steps once you look at the actual error message in CloudFormation.

**Comment by krogebry** [comment]
@karlvirgil Were you able to figure this out?
