### ISSUE TITLE
cfn master node is Retiring

### ISSUE THREAD

**Issue by mkaja** [awslabs/cfncluster#418]
cfn master node is Retiring: (aws maintenance ) 
This instance is scheduled for retirement after June - if we stop and start the master node - what will happen to running jobs and compute nodes ?

**Comment by hellmersjl3ds** [comment]
Whenever I've shutdown the master instance it and all compute nodes have been terminated, and I've had to redeploy the cluster.

Where are you seeing that the node is retiring?  I don't see that in any of my clusters.

**Comment by bwbarrett** [comment]
If the master node is terminated, you'll essentially lose control of the cluster and have to terminate the whole stack.

If the master node is shut down (from the OS point of view) or stopped (from AWS's point of view), you can keep going in *some cases*.  At least for SLURM and Toque (but I believe SGE also), the cluster nodes won't shut themselves down and if you stop/start the instance, the private IP won't change.  However, because the master is the NFS server, your apps may abort if they are performing IO when the NFS server is offline (because the instance is down).  The NFS server going down may cause you as much trouble as anything else.

ALso, if your master has local instance store (C3, I3, etc.), all bets are off.  You'll lose the instance store and likely lose something you wanted.

Trying to stop/start the master is not something we test on a regular basis.  It should work, but is also a tricky path when jobs are running because compute nodes depend on the master node for some services.
