### ISSUE TITLE
Accounting and Reporting Console (ARCo) on SGE

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#43]
http://arc.liv.ac.uk/repos/darcs/arco/www/index.html or at the very least the dbwriter.

**Comment by dougalb** [comment]
From the webpage that you referenced:

The ARCo web console mentioned below depends on a proprietary web server and is not supported in the free distribution. It may be possible to make it work under Tomcat or similar, but it is normally recommended to use the reporting database with your own query interface or the arcorun command line tool. Only the dbwriter component is currently distributed as a binary as it isn't clear whether or not arcorun can be run with free Java libraries. Note that support for the MySQL backend has been removed since the licence (GNU GPL) of its database connector is not compatible with the ARCo licence (SISSL).

As this not part of the default SGE install, if you would like to include it, I would suggest using pre/post install actions or building a custom AMI.

**Comment by cancan101** [comment]
@dougalb Okay, but the `dbwriter` component does not use the webserver.
