### ISSUE TITLE
cfn cluster is getting created and after few mins its getting roll back

### ISSUE THREAD

**Issue by mkaja** [awslabs/cfncluster#434]
cfn cluster is getting created and after 10 mins its getting roll back.

Received 1 FAILURE signal(s) out of 2. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

**Comment by sean-smith** [comment]
Specify the `--norollback` flag when you do a create. Then once the stack is in `CREATE_COMPLETE` or `CREATE_FAILED`, grab the ip address of the master instance from the console and ssh in. Start with the master instance and look at the `/var/log/cfn-init.log` and `/var/log/cfn-init-cmd.log` logs. 

Looks like the problem is with one of the compute nodes. You're going to want to ssh into those nodes and look at the same logs. Grab the private ip from ec2 console. 

This is either a problem with our bootstrap cookbook or your pre/post install script. Post your config (with aws creds removed) so we have more context.
