### ISSUE TITLE
Initial queue size

### ISSUE THREAD

**Issue by mukulagrawal78** [awslabs/cfncluster#451]
Can I make initial queue size to 0 ?
Can I make it 1?
Is this number dependent on choice of scheduler?

I am seeing consistent behavior across all functionality if I set to 2.
But I am not sure there is something wrong with my testing or if lower numbers are simply not accepted by some schedulers or cfncluster.

**Comment by bwbarrett** [comment]
0 or 1 as an initial queue size should work; it would be interesting to know more about the failures you're seeing.  SLURM, however, does react poorly to some configurations that become more evident when the cluster is scaled down significantly.  SLURM really has baked into its brain that compute nodes are hard to add (after all, you have to call Dell, wait for shipping, install the racks, do the setup, etc.), so it won't accept a job that's larger than the size of the node queue.  We have some semi-successful hacks at improving its behavior via configuration changes, but they don't always work, particularly when there are multiple jobs already submitted.  If you're looking to scale down a cluster significantly, I'd recommend using SGE or Torque (SGE in particular handles that case quite well, because Grid computing had it as a use case).

Regardless, details about what your configuration looks like and what error message you see would be helpful in figuring out what happened.
