### ISSUE TITLE
Control Size on Root Drive

### ISSUE THREAD

**Issue by cancan101** [awslabs/cfncluster#55]
Right now it looks like there is no setting to control the size of the root volume.

**Comment by dougalb** [comment]
Multiple users have asked for this. Added to the backlog.

**Comment by meissnert** [comment]
+1 on this. The workaround that I am using right now is that based on the original cfncluster AMI I created a new one with increased root partition that I boot up using the custom_ami option.

**Comment by johnbot1** [comment]
+1 here. I'd like to avoid creating custom AMIs if possible since it would no longer follow the cfn-cluster update cycle. I understand that expanding the root AMI size by default for all users would affect larger scale users by increasing costs so having a cluster parameter that expands the volume automatically on initialization would be a nice feature.

**Comment by dougalb** [comment]
This has been released as part of v0.0.22. You can specify master_root_volume_size and compute_root_volume_size as part of the cluster config section. 

http://cfncluster.readthedocs.org/en/latest/configuration.html#master-root-volume-size
