### ISSUE TITLE
Permit multiple s3 resources

### ISSUE THREAD

**Issue by vwong** [awslabs/cfncluster#73]
How would we specify an array value for `s3_read_resource` and `s3_read_write_resource`, if we needed to access to multiple ARNs?

Alternately, some mechanism to specify a custom role to attached to the EC2 instances can solve the problem too.

**Comment by dougalb** [comment]
The upcoming release of CfnCluster 1.0 supports using an existing EC2 IAM role as part of the cluster config. More details about the beta can be found here - https://forums.aws.amazon.com/ann.jspa?annID=3471 and the specific configuration option is here - http://cfncluster.readthedocs.org/en/develop/configuration.html#ec2-iam-role.

**Comment by dougalb** [comment]
Released in d14a9fcaec241fd3d87a0ca00e34c22eea0f4187

**Comment by jdhayes** [comment]
I am new to AWS and I am trying to use s3fs via a iam_role to mount a bucket on a cfncluster instance.
This feature to allow multiple s3_read_resource[s] still seems valid to me.

This is because s3fs requires 2 resources in order for it to mount via a iam_role and apply the proper permissions:
    arn:aws:s3:::mys3bucket
    arn:aws:s3:::mys3bucket/*

The first resource is needed for mounting. The second is needed for applying (retrieving meta-data?) proper permissions to all subsequent files and directories.

Am I understanding this right, that we can allow multiple s3 bucket resources if we create a custom instance role and a custom iam role?
Is there a better way to do this other creating a custom roles for all of this?

Any help is much appreciated.
Thanks
