### ISSUE TITLE
ami_cleanup.sh not on image

### ISSUE THREAD

**Issue by kdaily** [awslabs/cfncluster#82]
I'm using the most recent CentOS 6 us-east image (ami-a22114c8) to build a custom image. The instructions indicate that `/usr/local/sbin/ami_cleanup.sh` should be run before stopping the instance and creating an AMI, but this script is not available. Is it no longer necessary?

**Comment by dougalb** [comment]
With the move to Chef for all AMI build and bootstrapping, we're working towards removing or replacing the need for the script. Building of custom AMIs can now be done by adding/updating the chef receipes in https://github.com/awslabs/cfncluster-cookbook and then calling `./build_ami.sh`

Here is a gist of the original script, so you can see what it does: https://gist.github.com/dougalb/67382a3556823a8a36cd

**Comment by kdaily** [comment]
Thanks! I'll have to learn some Chef.

I am using Packer already (https://github.com/Sage-Bionetworks/CommonCompute)
- could I also just extend one of the existing packer configs with my stuff
(not using Chef, just remote shell script provisioners) and then use
`./build_ami.sh`?

**Comment by kdaily** [comment]
Sorry, I asked that already! (https://github.com/awslabs/cfncluster/issues/29). Thanks!

**Comment by f403** [comment]
Could you please update docs/source/ami_customization.rst ?

**Comment by mikerossgithub** [comment]
Doug - thank you for your answers. Is there any documentation that shows how to create a custom ami now that you are using Chef? My specific use case is CUDA installation which requires reboot. I modified the base AMI from https://github.com/awslabs/cfncluster/blob/master/amis.txt and followed the instructions on http://cfncluster.readthedocs.io/en/latest/ami_customization.html (but of course cannot do the last step since there is no ami_cleanup.sh). The result is the cluster create command works, but reports that sge is not installed when I try to run qhost. running the recommended sudo-apt-get command does not successfully install either.
