### ISSUE TITLE
"initial_queue_size" and "placement" config keys don't quite do what they say...

### ISSUE THREAD

**Issue by delocalizer** [awslabs/cfncluster#99]
At least when using torque scheduler (haven't tried others) the "initial_queue_size" and "placement" configuration keys don't seem to play very well together. For example, an initial_queue_size value of 1 and a placement value of "cluster" results in 1 Master, 1 Compute, and a queue containing both (which I would say had a size of 2!), whereas an initial_queue_size value of 0 and a placement value of "cluster" results in just the Master, but an empty queue (server_priv/nodes contains no entries)!
It seems like "initial_queue_size" is actually "number of compute nodes" regardless of the "placement" value. Additionally, there does not seem to be a way to configure a cluster with just a Master instance, and a queue with that in it.

**Comment by dougalb** [comment]
In CfnCluster the **MasterServer** does not participate in the scheduler queues. This is so that you can size them based on workload and shared NFS requirements. Also it helps to ensure that jobs running on the **MasterServer** don't overload it and cause issues with the scheduler operation. 

The [`initial_queue_size`](http://cfncluster.readthedocs.io/en/latest/configuration.html#initial-queue-size) parameter sets the initial number of instances in the **ComputeFleet** AutoScalingGroup. The [`placement`](http://cfncluster.readthedocs.io/en/latest/configuration.html#placement) parameter determines whether the **MasterServer** is included or not, when a [`placement_group`](http://cfncluster.readthedocs.io/en/latest/configuration.html#placement-group) is used.

**Comment by delocalizer** [comment]
Thanks for the clarification on this. I see now that if **MasterServer** is never included in the scheduler queues then there is no inconsistency. The confusion caused by seeing both **MasterServer** and **ComputeFleet** in the queue when specifying `initial_queue_size = 1` was my own doing, having forgotten that I added some code to post_install script to check if $cfn_node_type = "MasterServer" and the queue is configured with zero nodes, then add the current machine. But of course that always runs because when **MasterServer** is first created the queue always has zero nodes... doh.
